name: mapid_study_case
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ^3.44.0

dependencies:
  bloc: ^9.2.1
  dartz: ^0.10.1
  dio: ^5.11.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.3
  get_it: ^9.3.0
  intl: ^0.20.3
  json_annotation: ^4.12.0
  maplibre_gl: ^0.27.1

dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  build_runner: ^2.15.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.14.1
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env

